//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class wi15b666_flight
    {
        public System.Guid ID { get; set; }
        public string FlightNo { get; set; }
        public string Startpoint { get; set; }
        public string Endpoint { get; set; }
        public string Operator { get; set; }
    }
}
