//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingsDataRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trainings
    {
        public System.Guid Id { get; set; }
        public string Description { get; set; }
        public int Duration { get; set; }
        public int Level { get; set; }
        public string Exercises { get; set; }
    }
}
