//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkoutConsumer.SR_WorkoutService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SR_WorkoutService.IWorkoutService")]
    public interface IWorkoutService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkoutService/QueryWorkouts", ReplyAction="http://tempuri.org/IWorkoutService/QueryWorkoutsResponse")]
        Shared.Workout[] QueryWorkouts(string description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkoutService/QueryWorkouts", ReplyAction="http://tempuri.org/IWorkoutService/QueryWorkoutsResponse")]
        System.Threading.Tasks.Task<Shared.Workout[]> QueryWorkoutsAsync(string description);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWorkoutServiceChannel : WorkoutConsumer.SR_WorkoutService.IWorkoutService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WorkoutServiceClient : System.ServiceModel.ClientBase<WorkoutConsumer.SR_WorkoutService.IWorkoutService>, WorkoutConsumer.SR_WorkoutService.IWorkoutService {
        
        public WorkoutServiceClient() {
        }
        
        public WorkoutServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WorkoutServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WorkoutServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WorkoutServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Shared.Workout[] QueryWorkouts(string description) {
            return base.Channel.QueryWorkouts(description);
        }
        
        public System.Threading.Tasks.Task<Shared.Workout[]> QueryWorkoutsAsync(string description) {
            return base.Channel.QueryWorkoutsAsync(description);
        }
    }
}
