//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewFlightsWpf.SR_ServiceLogic {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Flight", Namespace="http://schemas.datacontract.org/2004/07/Shared")]
    [System.SerializableAttribute()]
    public partial class Flight : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EndPointField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid FlightIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FlightNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperatorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StartPointField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EndPoint {
            get {
                return this.EndPointField;
            }
            set {
                if ((object.ReferenceEquals(this.EndPointField, value) != true)) {
                    this.EndPointField = value;
                    this.RaisePropertyChanged("EndPoint");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid FlightID {
            get {
                return this.FlightIDField;
            }
            set {
                if ((this.FlightIDField.Equals(value) != true)) {
                    this.FlightIDField = value;
                    this.RaisePropertyChanged("FlightID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FlightNo {
            get {
                return this.FlightNoField;
            }
            set {
                if ((object.ReferenceEquals(this.FlightNoField, value) != true)) {
                    this.FlightNoField = value;
                    this.RaisePropertyChanged("FlightNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Operator {
            get {
                return this.OperatorField;
            }
            set {
                if ((object.ReferenceEquals(this.OperatorField, value) != true)) {
                    this.OperatorField = value;
                    this.RaisePropertyChanged("Operator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StartPoint {
            get {
                return this.StartPointField;
            }
            set {
                if ((object.ReferenceEquals(this.StartPointField, value) != true)) {
                    this.StartPointField = value;
                    this.RaisePropertyChanged("StartPoint");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SR_ServiceLogic.IServiceLogic")]
    public interface IServiceLogic {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLogic/QueryFlights", ReplyAction="http://tempuri.org/IServiceLogic/QueryFlightsResponse")]
        NewFlightsWpf.SR_ServiceLogic.Flight[] QueryFlights();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLogic/QueryFlights", ReplyAction="http://tempuri.org/IServiceLogic/QueryFlightsResponse")]
        System.Threading.Tasks.Task<NewFlightsWpf.SR_ServiceLogic.Flight[]> QueryFlightsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLogic/AddFlight", ReplyAction="http://tempuri.org/IServiceLogic/AddFlightResponse")]
        int AddFlight(string no, string sp, string ep, string op);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLogic/AddFlight", ReplyAction="http://tempuri.org/IServiceLogic/AddFlightResponse")]
        System.Threading.Tasks.Task<int> AddFlightAsync(string no, string sp, string ep, string op);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceLogicChannel : NewFlightsWpf.SR_ServiceLogic.IServiceLogic, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceLogicClient : System.ServiceModel.ClientBase<NewFlightsWpf.SR_ServiceLogic.IServiceLogic>, NewFlightsWpf.SR_ServiceLogic.IServiceLogic {
        
        public ServiceLogicClient() {
        }
        
        public ServiceLogicClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceLogicClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceLogicClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceLogicClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public NewFlightsWpf.SR_ServiceLogic.Flight[] QueryFlights() {
            return base.Channel.QueryFlights();
        }
        
        public System.Threading.Tasks.Task<NewFlightsWpf.SR_ServiceLogic.Flight[]> QueryFlightsAsync() {
            return base.Channel.QueryFlightsAsync();
        }
        
        public int AddFlight(string no, string sp, string ep, string op) {
            return base.Channel.AddFlight(no, sp, ep, op);
        }
        
        public System.Threading.Tasks.Task<int> AddFlightAsync(string no, string sp, string ep, string op) {
            return base.Channel.AddFlightAsync(no, sp, ep, op);
        }
    }
}
